
services:
  postgres:
    image: postgres:15
    container_name: batman_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: batman
      POSTGRES_PASSWORD: gotham
      POSTGRES_DB: batcave
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
